import * as THREE from 'three';

// Debug runs independently of the journey state machine: simulation remains frozen.
export function createDebug({camera,renderer,scene}) {
 document.body.classList.add('debug-mode');
 const style=document.createElement('style');style.textContent=`
 body.debug-mode> :not(#world):not(#loading):not(#debug-tools):not(#debug-image):not(script):not(style){display:none!important}
 #debug-tools{position:fixed;z-index:100;top:12px;left:12px;right:12px;background:#152027ed;color:white;padding:12px;border:1px solid #77908d;border-radius:10px;font:14px system-ui;display:flex;gap:9px;align-items:center;flex-wrap:wrap}
 #debug-tools button,#debug-tools select,#debug-tools input{font:inherit;max-width:130px}#debug-tools button{padding:7px 12px;cursor:pointer}#debug-tools small{flex-basis:100%}#debug-image{position:fixed;inset:0;width:100%;height:100%;z-index:90;touch-action:none}#debug-tools [hidden]{display:none!important}`;document.head.append(style);
 const panel=document.createElement('section');panel.id='debug-tools';panel.innerHTML=`<strong>Scene inspector</strong><select aria-label="Scene" id="debug-scene"><option>Nativity</option><option>Animal pen</option><option>Village</option><option>Overview</option><option>Start</option></select><label>Speed <input id="debug-speed" aria-label="Flight speed" type="range" min="1" max="60" value="12"></label><button id="debug-freeze">Freeze & annotate</button><span id="debug-drawing" hidden><select id="debug-tool" aria-label="Drawing tool"><option>Pen</option><option>Arrow</option><option>Line</option><option>Rectangle</option><option>Ellipse</option></select> <input id="debug-color" aria-label="Pen color" type="color" value="#ff5040"> <select id="debug-width" aria-label="Pen width"><option>3</option><option selected>6</option><option>12</option></select> <button id="debug-undo">Undo</button><button id="debug-clear">Clear</button></span><button id="debug-capture">Capture</button><a href="?">Return to game</a><small id="debug-help">WASD fly · Q/E down/up · hold right mouse to look · Shift boost · wheel adjusts speed. Simulation is frozen; no collision limits.</small><small id="debug-status" role="status"></small>`;document.body.append(panel);
 const $=id=>panel.querySelector('#debug-'+id),canvas=document.createElement('canvas');canvas.id='debug-image';canvas.hidden=true;document.body.append(canvas);const ctx=canvas.getContext('2d'),background=document.createElement('canvas'),bg=background.getContext('2d');
 const keys=new Set(),rotation=new THREE.Euler(0,0,0,'YXZ');let looking=false,frozen=false,marks=[],draft=null;
 const presets={'Nativity':[[-24,3,-72],[-34,1,-73]],'Animal pen':[[-20,7,-43],[-34,0,-53]],Village:[[12,15,12],[0,0,-15]],Overview:[[20,65,15],[-15,0,-35]],Start:[[4,5,35],[0,1,20]]};
 function jump(){const [p,t]=presets[$('scene').value];camera.position.fromArray(p);camera.lookAt(new THREE.Vector3(...t));rotation.setFromQuaternion(camera.quaternion,'YXZ');}jump();$('scene').onchange=jump;
 function clearInput(){keys.clear();looking=false;}window.addEventListener('blur',clearInput);
 window.addEventListener('keydown',e=>{if(/INPUT|SELECT|BUTTON/.test(e.target.tagName))return;if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();e.stopImmediatePropagation();keys.add(e.code);}},true);
 window.addEventListener('keyup',e=>keys.delete(e.code));renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
 renderer.domElement.addEventListener('pointerdown',e=>{document.activeElement?.blur();if(e.button===2&&!frozen){looking=true;renderer.domElement.setPointerCapture(e.pointerId);}});
 renderer.domElement.addEventListener('pointerup',()=>looking=false);renderer.domElement.addEventListener('pointermove',e=>{if(!looking||frozen)return;rotation.y-=e.movementX*.003;rotation.x=THREE.MathUtils.clamp(rotation.x-e.movementY*.003,-Math.PI/2+.01,Math.PI/2-.01);camera.quaternion.setFromEuler(rotation);});
 renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();$('speed').value=THREE.MathUtils.clamp(Number($('speed').value)*(e.deltaY<0?1.2:1/1.2),1,60);},{passive:false});
 function paintMark(m){ctx.strokeStyle=m.color;ctx.fillStyle=m.color;ctx.lineWidth=m.width;ctx.lineCap='round';ctx.lineJoin='round';const a=m.points[0],b=m.points.at(-1);ctx.beginPath();if(m.tool==='Rectangle')ctx.rect(a.x,a.y,b.x-a.x,b.y-a.y);else if(m.tool==='Ellipse')ctx.ellipse((a.x+b.x)/2,(a.y+b.y)/2,Math.abs(a.x-b.x)/2,Math.abs(a.y-b.y)/2,0,0,Math.PI*2);else {ctx.moveTo(a.x,a.y);for(const p of m.tool==='Pen'?m.points:[b])ctx.lineTo(p.x,p.y);}ctx.stroke();if(m.tool==='Arrow'){const angle=Math.atan2(b.y-a.y,b.x-a.x),size=m.width*4;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-size*Math.cos(angle-.5),b.y-size*Math.sin(angle-.5));ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-size*Math.cos(angle+.5),b.y-size*Math.sin(angle+.5));ctx.stroke();}}
 function redraw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(background,0,0);marks.forEach(paintMark);if(draft)paintMark(draft);}
 function freeze(){clearInput();renderer.render(scene,camera);canvas.width=background.width=renderer.domElement.width;canvas.height=background.height=renderer.domElement.height;bg.drawImage(renderer.domElement,0,0);marks=[];draft=null;frozen=true;canvas.hidden=false;$('drawing').hidden=false;$('scene').disabled=true;$('freeze').textContent='Resume camera';redraw();}
 $('freeze').onclick=()=>{if(!frozen)freeze();else {frozen=false;canvas.hidden=true;$('drawing').hidden=true;$('scene').disabled=false;$('freeze').textContent='Freeze & annotate';}};
 function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};}
 canvas.onpointerdown=e=>{if(e.button!==0)return;canvas.setPointerCapture(e.pointerId);draft={tool:$('tool').value,color:$('color').value,width:Number($('width').value)*canvas.width/innerWidth,points:[point(e)]};};canvas.onpointermove=e=>{if(draft){draft.points.push(point(e));redraw();}};canvas.onpointerup=e=>{if(draft){draft.points.push(point(e));marks.push(draft);draft=null;redraw();}};canvas.onpointercancel=()=>{draft=null;redraw();};$('undo').onclick=()=>{marks.pop();redraw();};$('clear').onclick=()=>{marks=[];redraw();};
 $('capture').onclick=async()=>{if(!frozen)freeze();const button=$('capture');button.disabled=true;$('status').textContent='Saving…';try{const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Could not encode screenshot');const capability=await fetch(location.href,{method:'HEAD'});if(capability.headers.get('X-Shepherd-Capture')==='1'){const response=await fetch('/__debug/capture',{method:'POST',headers:{'Content-Type':'image/png'},body:blob});if(!response.ok)throw Error(`Capture server returned ${response.status}. Run this prototype with its serve.py.`);const result=await response.json();$('status').textContent='Saved '+result.path;}else {const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='shepherd-capture.png';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);$('status').textContent='Downloaded PNG. Local serve.py saves directly into captures/.';}}catch(error){$('status').textContent=error.message;}finally{button.disabled=false;}};
 return {update(dt){if(frozen)return;const v=new THREE.Vector3(Number(keys.has('KeyD'))-Number(keys.has('KeyA')),0,Number(keys.has('KeyS'))-Number(keys.has('KeyW')));v.applyQuaternion(camera.quaternion);v.y+=Number(keys.has('KeyE'))-Number(keys.has('KeyQ'));if(v.lengthSq())camera.position.addScaledVector(v.normalize(),Number($('speed').value)*dt*(keys.has('ShiftLeft')||keys.has('ShiftRight')?4:1));}};
}
