import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { VRButton } from 'three/addons/webxr/VRButton.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import { Sky } from 'three/addons/objects/Sky.js';
import { makeActor, animateTeacher, animateListener, instanceCrowd, type Actor } from './actors';
import { loadFreeActors } from './actors-v2';
import { EDIT } from './performance';
import { parseVtt, activeCue, type Cue } from './media';
export type Experience = { version:(v:'v1'|'v2')=>void; closeView:()=>void; play:()=>Promise<void>; toggle:()=>void; seek:(t:number)=>void; volume:(v:number)=>void; captions:(v:boolean)=>void; walk:()=>void; reset:()=>void; move:(d:string,v:boolean)=>void; dispose:()=>void };
type Events = {ready:()=>void;state:(b:boolean)=>void;time:(t:number)=>void;cue:(s:string)=>void;status:(s:string)=>void;walking:(v:boolean)=>void;versionReady:(v:boolean)=>void};
export function groundHeight(x:number,z:number){const r=Math.hypot(x,z);return .045*Math.sin(x*.6)*Math.sin(z*.45)+Math.max(0,r-14)*.07+Math.max(0,r-24)*(.15+.12*Math.sin(x*.05+z*.07));}
export async function createExperience(host:HTMLElement,vrHost:HTMLElement,events:Events):Promise<Experience>{
 const scene=new THREE.Scene(); scene.background=new THREE.Color('#b6c4b6');scene.fog=new THREE.FogExp2('#b8c1a7',.012);
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');host.appendChild(renderer.domElement);
 renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Drag to look; use WASD or arrow keys to walk.');
 const camera=new THREE.PerspectiveCamera(62,host.clientWidth/host.clientHeight,.07,350);const rig=new THREE.Group();rig.add(camera);scene.add(rig);camera.position.y=1.65;
 const reset=()=>{rig.position.set(2.6,groundHeight(2.6,4.7),4.7);rig.rotation.set(0,0,0);camera.position.set(0,1.65,0);camera.rotation.set(-.025,.54,0,'YXZ');};reset();
 const hemi=new THREE.HemisphereLight('#e2eddf','#82734c',2.7);scene.add(hemi);
 const sun=new THREE.DirectionalLight('#ffe5b1',3.2);sun.position.set(-24,35,-18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-26;sun.shadow.camera.right=26;sun.shadow.camera.top=26;sun.shadow.camera.bottom=-26;sun.shadow.camera.far=100;sun.shadow.normalBias=.035;sun.shadow.bias=-.00015;scene.add(sun);
 const sky=new Sky();sky.scale.setScalar(300);scene.add(sky);sky.material.uniforms.turbidity.value=5;sky.material.uniforms.rayleigh.value=1.1;sky.material.uniforms.mieCoefficient.value=.006;sky.material.uniforms.mieDirectionalG.value=.8;sky.material.uniforms.sunPosition.value.copy(sun.position).normalize();
 let seed=612;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
 const terrain=new THREE.PlaneGeometry(240,240,170,170);terrain.rotateX(-Math.PI/2);const points=terrain.attributes.position;const colors=[];const color=new THREE.Color();
 for(let i=0;i<points.count;i++){const x=points.getX(i),z=points.getZ(i);points.setY(i,groundHeight(x,z));const r=Math.hypot(x,z);const patch=Math.sin(x*.7+Math.sin(z*.35))*Math.cos(z*.4)+random()*.45;const path=Math.abs(x-1.1*Math.sin(z*.19))<1.5&&z>0; color.set(path?'#ac9770':r<10?(patch>.5?'#90905c':'#ada078'):(patch>.4?'#6f7d49':'#92915e'));color.multiplyScalar(.9+random()*.14);colors.push(color.r,color.g,color.b);}
 terrain.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));terrain.computeVertexNormals();const earth=new THREE.Mesh(terrain,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}));earth.receiveShadow=true;scene.add(earth);
 const statics=new THREE.Group();scene.add(statics);
 const rockGeo=new THREE.IcosahedronGeometry(1,0),stoneMat=new THREE.MeshStandardMaterial({color:'#aea891',roughness:1,flatShading:true});const rocks=new THREE.InstancedMesh(rockGeo,stoneMat,550);const dummy=new THREE.Object3D();
 for(let i=0;i<550;i++){let x=(random()-.5)*100,z=(random()-.5)*100;if(Math.hypot(x,z)<2){x+=8;}const scale=.08+random()**3*.7;dummy.position.set(x,groundHeight(x,z)+scale*.16,z);dummy.scale.set(scale*1.4,scale*.65,scale);dummy.rotation.set(random(),random()*6,random());dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix);}rocks.castShadow=true;rocks.receiveShadow=true;scene.add(rocks);
 // Stone terrace edges and low, irregular field walls.
 for(let row=0;row<3;row++)for(let i=0;i<80;i++){const x=-28+i*.7,z=-12-row*7+Math.sin(x*.12)*2;const stone=new THREE.Mesh(rockGeo,stoneMat);stone.position.set(x,groundHeight(x,z)+.25,z);stone.scale.set(.43+random()*.14,.3+random()*.2,.37);stone.rotation.set(random()*.3,random()*3,0);statics.add(stone);}
 const grassGeo=new THREE.BufferGeometry();grassGeo.setAttribute('position',new THREE.Float32BufferAttribute([-.055,0,0,.055,0,0,.015,.36,.035,0,0,-.04,0,0,.04,.04,.28,0],3));grassGeo.computeVertexNormals();const grass=new THREE.InstancedMesh(grassGeo,new THREE.MeshStandardMaterial({color:'#7c8451',side:THREE.DoubleSide,roughness:1}),8000);
 for(let i=0;i<8000;i++){let x=(random()-.5)*105,z=(random()-.5)*105;const path=Math.abs(x-1.1*Math.sin(z*.19))<1.5&&z>0;if(path){x+=3;}dummy.position.set(x,groundHeight(x,z),z);const s=.5+random();dummy.scale.set(s,s,s);dummy.rotation.set(0,random()*Math.PI,0);dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix);}scene.add(grass);
 const woodMat=new THREE.MeshStandardMaterial({color:'#514730',roughness:1});const clothMat=new THREE.MeshStandardMaterial({color:'#67533b',side:THREE.DoubleSide,roughness:1});
 function pole(a:THREE.Vector3,b:THREE.Vector3,r=.05){const d=b.clone().sub(a);const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r*1.15,d.length(),7),woodMat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());statics.add(m);}
 function shelter(x:number,z:number){const y=groundHeight(x,z);for(const dx of [-2.7,2.7])for(const dz of [-1.8,1.8])pole(new THREE.Vector3(x+dx,y,z+dz),new THREE.Vector3(x+dx,y+2.5,z+dz));const g=new THREE.PlaneGeometry(5.8,4.1,12,10);g.rotateX(-Math.PI/2);const p=g.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,2.6-.35*Math.sin((p.getX(i)/5.8+.5)*Math.PI)+.07*Math.sin(p.getZ(i)*3));g.computeVertexNormals();const awning=new THREE.Mesh(g,clothMat);awning.position.set(x,y,z);statics.add(awning);}
 shelter(-9,-5);shelter(13,-11);
 const loader=new GLTFLoader();const names=['jesus','listener-ochre','listener-sage','listener-clay','listener-blue','listener-linen','listener-elder','listener-broad','listener-young','listener-woman','listener-traveller','olive','jar'];
 let prototypes:THREE.Object3D[];
 try{prototypes=await Promise.all(names.map(async name=>(await loader.loadAsync(`./models/${name}.glb?v=articulated-2`)).scene));}catch(error){renderer.dispose();host.replaceChildren();throw error;}
 const classicGroup=new THREE.Group();classicGroup.name='V1 · procedural Blender characters';scene.add(classicGroup);
 const teacherActor=makeActor(prototypes[0]);const teacher=teacherActor.root;teacher.name='Jesus — articulated teaching performance';classicGroup.add(teacher);
 const colliders:{x:number;z:number;r:number}[]=[{x:0,z:0,r:.65}];
 const positions:number[][]=[[-2.7,2.8],[-3.7,4.1],[3.2,2.3],[4.4,3.5],[5.4,5.7],[-1,5.5],[-3.9,6.6],[-6,2],[-4.5,-.5],[4,-.7],[5,-3],[-3,-3],[-1.6,-4],[1.5,-4.5]];
 for(let row=0;row<3;row++)for(let i=0;i<12;i++){const a=(i/12)*Math.PI*2+.15*row,r=8+row*2.7;const x=Math.cos(a)*r,z=Math.sin(a)*r;if(x>1&&x<5&&z>5)continue;positions.push([x+(random()-.5)*.4,z+(random()-.5)*.4]);}
 const crowdGroups:Actor[][]=Array.from({length:10},()=>[]),crowd:Actor[]=[];
 positions.forEach(([x,z],i)=>{
  const type=i%10;const actor=makeActor(prototypes[1+type],i*1.731+type*.73);actor.scale=i%17===0?.83:.9+random()*.15;
  actor.root.position.set(x,groundHeight(x,z),z);actor.baseYaw=Math.atan2(-x,-z)+(random()-.5)*.4;actor.root.rotation.y=actor.baseYaw;
  actor.root.scale.set(actor.scale*(.94+random()*.12),actor.scale,actor.scale*(.95+random()*.1));
  if(i===9){actor.seated=true;actor.root.position.set(2.05,groundHeight(2.05,-.45)-.42,-.45);actor.baseYaw=-1.3;actor.root.rotation.y=actor.baseYaw;}
  crowdGroups[type].push(actor);crowd.push(actor);colliders.push({x:actor.root.position.x,z:actor.root.position.z,r:.38});
 });
 const updateCrowdInstances=instanceCrowd(classicGroup,crowdGroups);
 let freeActors:Awaited<ReturnType<typeof loadFreeActors>>|null=null,version:'v1'|'v2'='v1';
 const setVersion=(v:'v1'|'v2')=>{if(v==='v2'&&!freeActors)return;version=v;classicGroup.visible=v==='v1';if(freeActors)freeActors.group.visible=v==='v2';};
 const audioAnchor=new THREE.Group();scene.add(audioAnchor);
 for(let i=0;i<38;i++){const angle=random()*Math.PI*2,r=19+random()*48;const x=Math.cos(angle)*r,z=Math.sin(angle)*r;const tree=prototypes[11].clone(true);tree.position.set(x,groundHeight(x,z),z);tree.scale.setScalar(.9+random()*.65);tree.rotation.y=random()*6;statics.add(tree);colliders.push({x,z,r:.4});}
 for(const [x,z] of [[-7,-4],[-8,-4.5],[11,-9],[-9,-3]]){const jar=prototypes[12].clone(true);jar.position.set(x,groundHeight(x,z),z);statics.add(jar);}
 // Only scenery is static; the independently articulated crowd uses instancing above.
 statics.updateMatrixWorld(true);const batches=new Map<THREE.Material,THREE.BufferGeometry[]>();
 statics.traverse(o=>{if(!(o instanceof THREE.Mesh))return;const geometry=o.geometry.clone().applyMatrix4(o.matrixWorld);if(Array.isArray(o.material)){for(const group of geometry.groups){const g=geometry.toNonIndexed();const attrs=['position','normal','uv'];const chunk=new THREE.BufferGeometry();for(const key of attrs){const attr=g.getAttribute(key);if(attr)chunk.setAttribute(key,new THREE.BufferAttribute((attr.array as Float32Array).slice(group.start*attr.itemSize,(group.start+group.count)*attr.itemSize),attr.itemSize));}g.dispose();const material=o.material[group.materialIndex??0];if(!batches.has(material))batches.set(material,[]);batches.get(material)!.push(chunk);}geometry.dispose();}else{if(!batches.has(o.material))batches.set(o.material,[]);batches.get(o.material)!.push(geometry.index?geometry.toNonIndexed():geometry);}});
 scene.remove(statics);for(const [material,geometries]of batches){for(const g of geometries){for(const attr of Object.keys(g.attributes))if(!['position','normal'].includes(attr))g.deleteAttribute(attr);}const merged=mergeGeometries(geometries);if(merged){const mesh=new THREE.Mesh(merged,material);mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);}geometries.forEach(g=>g.dispose());}
 teacher.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});
 const media=document.createElement('audio');media.preload='auto';media.src='./audio/sermon-teaching.wav';media.setAttribute('aria-hidden','true');media.style.display='none';host.appendChild(media);
 let disposed=false,cues:Cue[]=[],showCaptions=true,lastCue='',audio:THREE.PositionalAudio|null=null,listener:THREE.AudioListener|null=null;
 const subtitleCanvas=document.createElement('canvas');subtitleCanvas.width=1536;subtitleCanvas.height=320;const ctx=subtitleCanvas.getContext('2d')!;const texture=new THREE.CanvasTexture(subtitleCanvas);texture.colorSpace=THREE.SRGBColorSpace;const subtitleMesh=new THREE.Mesh(new THREE.PlaneGeometry(1.8,.375),new THREE.MeshBasicMaterial({map:texture,transparent:true,depthTest:false,depthWrite:false}));subtitleMesh.position.set(0,-.48,-2);subtitleMesh.renderOrder=999;subtitleMesh.visible=false;camera.add(subtitleMesh);
 function paintCaption(text:string){ctx.clearRect(0,0,1536,320);if(text){ctx.fillStyle='rgba(12,22,16,.86)';ctx.fillRect(0,0,1536,320);ctx.fillStyle='#f7f3e8';ctx.font='48px Arial';ctx.textAlign='center';const lines:string[]=[];let line='';for(const word of text.split(' ')){if(ctx.measureText(`${line} ${word}`).width>1400){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);lines.slice(0,4).forEach((l,i)=>ctx.fillText(l,768,160-(lines.length-1)*30+i*60));}texture.needsUpdate=true;}
 const abort=new AbortController();fetch('./audio/sermon-teaching.vtt',{signal:abort.signal}).then(async r=>{if(!r.ok)throw Error();cues=parseVtt(await r.text());if(!cues.length)throw Error();}).catch(()=>{if(!disposed)events.status('Captions unavailable · audio can still play');});
 let envelope:{step:number;values:number[]}={step:.02,values:[]};
 fetch('./audio/speech-envelope.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{if(typeof data==='object'&&data!==null&&'step' in data&&'values' in data&&typeof data.step==='number'&&data.step>0&&Array.isArray(data.values)&&data.values.every(v=>typeof v==='number'&&Number.isFinite(v)))envelope={step:data.step,values:data.values};}).catch(()=>{});
 let volume=.85;
 async function play(){if(disposed)return;try{if(!listener){listener=new THREE.AudioListener();camera.add(listener);audio=new THREE.PositionalAudio(listener);audio.setMediaElementSource(media);audio.setRefDistance(7);audio.setRolloffFactor(.45);audio.setMaxDistance(50);audio.setVolume(volume);audio.position.set(0,1.55,0);audioAnchor.add(audio);}await listener.context.resume();if(media.ended)media.currentTime=0;await media.play();}catch{events.status('Audio could not start · press play to retry');}}
 const toggle=()=>{if(media.paused)void play();else media.pause();};
 media.addEventListener('playing',()=>{events.state(true);events.status('Jesus’ teaching · 11 edited excerpts');});media.addEventListener('pause',()=>events.state(false));media.addEventListener('waiting',()=>events.status('Loading the teaching audio…'));media.addEventListener('ended',()=>{events.state(false);events.status('Sermon complete · replay or keep exploring');});media.addEventListener('error',()=>events.status('Audio unavailable · check your connection and retry'));
 const keys=new Set<string>();const movement=new Set<string>();let dragging=false,lastX=0,lastY=0;
 const onKey=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(target.closest('button,input,[role=slider],a'))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.code==='Space'){e.preventDefault();toggle();}};
 const onUp=(e:KeyboardEvent)=>keys.delete(e.code);const clear=()=>{keys.clear();movement.clear();dragging=false;};
 const look=(dx:number,dy:number)=>{if(renderer.xr.isPresenting)return;camera.rotation.y-=dx*.003;camera.rotation.x=THREE.MathUtils.clamp(camera.rotation.x-dy*.003,-1.25,1.25);};
 const down=(e:PointerEvent)=>{if(e.button!==0)return;dragging=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.focus({preventScroll:true});renderer.domElement.setPointerCapture(e.pointerId);};
 const pointer=(e:PointerEvent)=>{if(document.pointerLockElement===renderer.domElement)look(e.movementX,e.movementY);else if(dragging){look(e.clientX-lastX,e.clientY-lastY);lastX=e.clientX;lastY=e.clientY;}};
 const up=()=>{dragging=false;};const locked=()=>events.walking(document.pointerLockElement===renderer.domElement);
 window.addEventListener('keydown',onKey);window.addEventListener('keyup',onUp);window.addEventListener('blur',clear);document.addEventListener('pointerlockchange',locked);document.addEventListener('pointermove',pointer);renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);
 const onVisibility=()=>{clear();if(document.hidden)media.pause();};document.addEventListener('visibilitychange',onVisibility);
 const resize=new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();});resize.observe(host);
 const vrButton=VRButton.createButton(renderer,{optionalFeatures:['local-floor']});vrHost.appendChild(vrButton);
 const onXRStart=()=>{clear();camera.position.set(0,0,0);camera.rotation.set(0,0,0);rig.rotation.y=.54;void play();};const onXREnd=()=>{camera.position.set(0,1.65,0);camera.rotation.set(-.045,0,0,'YXZ');subtitleMesh.visible=false;clear();};renderer.xr.addEventListener('sessionstart',onXRStart);renderer.xr.addEventListener('sessionend',onXREnd);
 for(let i=0;i<2;i++){const controller=renderer.xr.getController(i);controller.addEventListener('selectstart',toggle);rig.add(controller);}
 let snapReady=true,previous=0,lastUi=0;const direction=new THREE.Vector3();const quaternion=new THREE.Quaternion();
 const canStand=(x:number,z:number)=>Math.hypot(x,z)<25&&!colliders.some(c=>Math.hypot(x-c.x,z-c.z)<c.r+.23);
 function moveBy(dx:number,dz:number){const x=rig.position.x+dx,z=rig.position.z+dz;if(canStand(x,rig.position.z))rig.position.x=x;if(canStand(rig.position.x,z))rig.position.z=z;rig.position.y=groundHeight(rig.position.x,rig.position.z);}
 renderer.setAnimationLoop((now)=>{const dt=Math.min((now-previous)/1000,.05);previous=now;let forward=0,side=0;
 if(keys.has('KeyW')||keys.has('ArrowUp')||movement.has('forward'))forward-=1;if(keys.has('KeyS')||keys.has('ArrowDown')||movement.has('back'))forward+=1;if(keys.has('KeyA')||keys.has('ArrowLeft')||movement.has('left'))side-=1;if(keys.has('KeyD')||keys.has('ArrowRight')||movement.has('right'))side+=1;
 if(renderer.xr.isPresenting){const session=renderer.xr.getSession();for(const source of session?.inputSources??[]){if(!source.gamepad)continue;const axes=source.gamepad.axes;const x=axes.length>=4?axes[2]:axes[0]??0;const y=axes.length>=4?axes[3]:axes[1]??0;if(source.handedness==='left'){side=Math.abs(x)>.18?x:0;forward=Math.abs(y)>.18?y:0;}if(source.handedness==='right'){if(Math.abs(x)<.3)snapReady=true;else if(Math.abs(x)>.7&&snapReady){rig.rotation.y-=Math.sign(x)*Math.PI/6;snapReady=false;}}}}
 if(forward||side){camera.getWorldQuaternion(quaternion);direction.set(0,0,-1).applyQuaternion(quaternion);const yaw=Math.atan2(-direction.x,-direction.z);const speed=(renderer.xr.isPresenting?1.25:keys.has('ShiftLeft')||keys.has('ShiftRight')?2.8:1.65)*dt/Math.max(1,Math.hypot(side,forward));moveBy((side*Math.cos(yaw)+forward*Math.sin(yaw))*speed,(-side*Math.sin(yaw)+forward*Math.cos(yaw))*speed);}
 const words=activeCue(cues,media.currentTime);const index=Math.floor(media.currentTime/envelope.step);
 const energy=!media.paused&&!media.seeking&&words?(envelope.values[index]??0):0;
 animateTeacher(teacherActor,media.currentTime,now/1000,energy,groundHeight);
 audioAnchor.position.copy(teacher.position);
 if(version==='v2'&&freeActors){freeActors.update(media.currentTime,now/1000,energy);freeActors.teacher.bones.Head.getWorldPosition(audioAnchor.position);audioAnchor.position.y-=1.49;}
 colliders[0].x=teacher.position.x;colliders[0].z=teacher.position.z;
 if(version==='v1'){for(const actor of crowd)animateListener(actor,now/1000,teacher.position);updateCrowdInstances();}
 if(now-lastUi>80){events.time(media.currentTime);const text=showCaptions?activeCue(cues,media.currentTime):'';if(text!==lastCue){lastCue=text;events.cue(text);paintCaption(text);}subtitleMesh.visible=renderer.xr.isPresenting&&showCaptions&&!!text;lastUi=now;}renderer.render(scene,camera);
 });events.ready();events.status('Loading V2 characters…');
 void loadFreeActors(loader,crowd.map(a=>({x:a.root.position.x,z:a.root.position.z,scale:a.scale,yaw:a.baseYaw,seated:a.seated})),groundHeight).then(layer=>{if(disposed){layer.dispose();return;}freeActors=layer;scene.add(layer.group);setVersion(version);events.versionReady(true);events.status('Jesus’ teaching · V1 Blender');}).catch(()=>{if(!disposed){events.versionReady(false);events.status('V2 models could not load · V1 remains available; reload to retry');}});
 return {version:setVersion,closeView:()=>{const p=teacher.position;rig.position.set(p.x+.8,groundHeight(p.x+.8,p.z+2.1),p.z+2.1);rig.rotation.set(0,0,0);camera.rotation.set(-.035,Math.atan2(.8,2.1),0,'YXZ');},play,toggle,seek:t=>{if(Number.isFinite(t)&&media.readyState>0)media.currentTime=THREE.MathUtils.clamp(t,0,Number.isFinite(media.duration)?media.duration:EDIT.duration);},volume:v=>{volume=THREE.MathUtils.clamp(v,0,1);audio?.setVolume(volume);},captions:v=>{showCaptions=v;},walk:()=>{const result=renderer.domElement.requestPointerLock?.();result?.catch(()=>events.status('Drag to look and use WASD to walk'));},reset,move:(d,v)=>{if(v)movement.add(d);else movement.delete(d);},dispose:()=>{disposed=true;freeActors?.dispose();abort.abort();renderer.setAnimationLoop(null);media.pause();media.removeAttribute('src');media.load();audio?.disconnect();resize.disconnect();window.removeEventListener('keydown',onKey);window.removeEventListener('keyup',onUp);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',onVisibility);document.removeEventListener('pointerlockchange',locked);document.removeEventListener('pointermove',pointer);if(document.pointerLockElement===renderer.domElement)document.exitPointerLock();if(renderer.xr.isPresenting)void renderer.xr.getSession()?.end();const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();scene.traverse(o=>{if(o instanceof THREE.Mesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());texture.dispose();renderer.dispose();host.replaceChildren();vrHost.replaceChildren();}};
}
