import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {Journey,NODE,NODES,EDGES,links,lanePoints} from '../src/journey-model.mjs';
let checks=0;const check=fn=>{fn();checks++;};
function walk(j,to){const e=j.options.find(e=>e.to===to);assert(e,`unavailable ${j.at} -> ${to}`);assert(j.commit(e));assert.equal(j.phase,'walking',`${j.at} -> ${to}`);for(let i=0;i<2000&&j.travel;i++)j.step(.05);assert.equal(j.at,to);}
function finishGate(j){for(let i=0;i<3000&&j.phase==='gate-sequence';i++)j.step(.05);assert.equal(j.phase,'choice');}
function inspect(j){assert(j.inspect());if(j.phase==='gate-sequence'){finishGate(j);return;}if(j.phase!=='arrival')assert(j.closeInspection());}
function prepare(j,order=['wick','oil']){walk(j,'gate');walk(j,'hearth');for(const item of order){walk(j,item);inspect(j);walk(j,'hearth');}inspect(j);assert(j.lantern);walk(j,'gate');}
check(()=>{assert.equal(new Set(NODES.map(n=>n.id)).size,NODES.length);for(const e of EDGES){assert(NODE[e.a]&&NODE[e.b]);assert(!('cost' in e));}});
check(()=>{const j=new Journey();j.start();walk(j,'gate');const before=j.distance;j.commit(j.options.find(e=>e.to==='well'));assert.equal(j.phase,'inspect');assert.equal(j.distance,before);assert.match(j.inspection.body,/no light/);j.closeInspection();walk(j,'hearth');inspect(j);assert(!j.lantern);walk(j,'wick');inspect(j);walk(j,'hearth');j.inspect();assert(!j.lantern);assert.match(j.inspection.body,/oil/);});
check(()=>{for(const order of [['wick','oil'],['oil','wick']]){const j=new Journey();j.start();prepare(j,order);assert.deepEqual([...j.inventory].sort(),['lantern','oil','wick']);assert.equal(j.discoveries.size,0,'supplies must not reveal routes');}});
check(()=>{const j=new Journey();j.start();j.commit();assert(!j.commit());j.step(1);j.paused=true;const before=j.snapshot();j.step(100);assert.deepEqual(j.snapshot(),before);});
check(()=>{const j=new Journey();j.start();prepare(j);walk(j,'olive');walk(j,'market');const d=j.distance;j.commit(j.options.find(e=>e.to==='arch'));assert.equal(j.phase,'inspect');assert.equal(j.distance,d);assert(!j.gateOpen);});
check(()=>{const j=new Journey();j.start();j.at='arch';j.inspect();const start=j.position;j.paused=true;j.step(10);assert.deepEqual(j.position,start);j.paused=false;let sawLight=false,sawReturn=false;for(let i=0;i<3000&&j.gateSequence;i++){j.step(.05);if(j.gateSequence?.stage==='light')sawLight=true;if(j.gateSequence?.stage==='return'){sawReturn=true;assert(j.gateOpen);}}assert(sawLight&&sawReturn);assert.equal(j.position.x,NODE.arch.x);assert.equal(j.position.z,NODE.arch.z);assert.equal(j.followers.length,2);assert(j.followers.every(f=>f.visible&&!f.moving&&Math.hypot(f.x-NODE.goal.x,f.z-NODE.goal.z)<2));j.reset();assert.equal(j.followers.length,0);assert(!j.gateSequence);});
const routes=[];
check(()=>{const j=new Journey();j.start();prepare(j);for(const to of ['well','square','pen'])walk(j,to);assert(!j.options.some(e=>e.to==='arch'));j.inspect();assert.equal(j.reward.kind,'route');j.closeInspection();walk(j,'arch');j.commit(j.options.find(e=>e.to==='goal'));assert.equal(j.phase,'gate-sequence');assert(!j.gateOpen);finishGate(j);assert(j.gateOpen);assert.equal(j.at,'arch');walk(j,'goal');assert.equal(j.phase,'choice');inspect(j);assert.equal(j.phase,'arrival');routes.push({route:'animal-fold with preparation and welcome gate',metres:Math.round(j.distance)});});
check(()=>{const j=new Journey();j.start();prepare(j,['oil','wick']);for(const to of ['olive','lookout'])walk(j,to);inspect(j);for(const to of ['olive','market','square','arch'])walk(j,to);inspect(j);walk(j,'goal');inspect(j);assert.equal(j.phase,'arrival');routes.push({route:'overlook with preparation and welcome gate',metres:Math.round(j.distance)});});
check(()=>{const j=new Journey();j.start();prepare(j);walk(j,'ridge');walk(j,'pen');inspect(j);j.recover();assert(j.lantern&&j.discoveries.has('rear'));assert.equal(j.at,'gate');j.reset();assert.deepEqual(j.snapshot(),new Journey().snapshot());});
check(()=>{const j=new Journey();j.start();walk(j,'gate');walk(j,'hearth');walk(j,'wick');j.inspect();assert(j.reward);j.closeInspection();j.inspect();assert.equal(j.reward,null,'repeated inspection must not celebrate again');j.closeInspection();j.commit(j.options[0]);let ran=false;for(let i=0;i<300&&j.travel;i++){j.step(.05);ran ||= (j.travel?.speed||0)>3.6;}assert(ran,'familiar return lane should allow a brief run');});
// Independent finite-state graph: inventory bits wick/oil/lantern, knowledge bits overlook/rear/gate.
const key=([at,i,k])=>`${at}:${i}:${k}`;
function next([at,i,k]){const out=[];if(at==='wick')out.push([at,i|1,k]);if(at==='oil')out.push([at,i|2,k]);if(at==='hearth'&&(i&3)===3)out.push([at,i|4,k]);if(at==='lookout')out.push([at,i,k|1]);if(at==='pen')out.push([at,i,k|2]);if(at==='arch')out.push([at,i,k|4]);for(const e of links(at)){if(at==='gate'&&!(i&4)&&!['field','hearth'].includes(e.to))continue;if(e.requires==='overlook'&&!(k&1)||e.requires==='rear'&&!(k&2)||['gate','welcome'].includes(e.requires)&&!(k&4))continue;out.push([e.to,i,k]);}return out;}
const queue=[['field',0,0]],states=new Map(),reverse=new Map();while(queue.length){const state=queue.shift(),id=key(state);if(states.has(id))continue;states.set(id,state);for(const n of next(state)){const nk=key(n);if(!reverse.has(nk))reverse.set(nk,[]);reverse.get(nk).push(id);if(!states.has(nk))queue.push(n);}}
check(()=>{const q=[...states].filter(([,s])=>s[0]==='goal').map(([id])=>id),winning=new Set();while(q.length){const id=q.shift();if(winning.has(id))continue;winning.add(id);q.push(...(reverse.get(id)||[]));}for(const id of states.keys())assert(winning.has(id),`softlock ${id}`);});
check(()=>{for(const e of EDGES)for(const p of lanePoints(e))assert(Number.isFinite(p.x)&&Number.isFinite(p.z));});
const report={status:'passed',checks,knowledgeStates:states.size,routes,limits:'State safety and reachability do not establish enjoyment, clue readability or actual remote performance.'};writeFileSync(new URL('./journey-verification.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
